# fly.toml app configuration file generated for interview-bot-prod on 2025-07-02T20:50:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'interview-bot-prod'
primary_region = 'gru'

[build]

[env]
  DEBUG = 'false'
  ENVIRONMENT = 'production'
  HOST = '0.0.0.0'
  PORT = '8000'

[[mounts]]
  source = 'data'
  destination = '/app/logs'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
