# fly.toml app configuration file
app = "interview-bot-prod"
primary_region = "gru"

[build]

[env]
  DEBUG = "false"
  ENVIRONMENT = "production"
  HOST = "0.0.0.0"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Configurações de timeout para áudios longos
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Configuração para manter dados temporários
[[mounts]]
  source = "data"
  destination = "/app/logs"